name: 'Check'

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Cache bun dependencies
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

# This job is for checking the code style, type and lint errors.
  check-all: 
    needs: install-dependencies
    runs-on: ubuntu-latest
    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore bun dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun

      - name: üíÖüèª Type Check, Lint and format
        run: bun run checkAll 
  pa11y-ci: 
    needs: install-dependencies
    runs-on: ubuntu-latest
    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore bun dependencies
        id: bun-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun
      
      - name: Install dependencies
        run: bun install -g pa11y-ci
        
      - name: Build
        run: bun run build

      - name: üê£ Pa11y Test
        run: bun run start && sleep 3; bun pa11y

# This job is for executing tests.
  # test: 
  #   needs: install-dependencies
  #   runs-on: ubuntu-latest
  # env:
  #   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  #   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  #   steps:
  #     - name: Checkout Commit
  #       uses: actions/checkout@v4
          # with:
          #   fetch-depth: 2

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v1
  #       with:
  #         bun-version: latest

  #     - name: Restore bun dependencies
  #       id: bun-cache
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
  #         restore-keys: ${{ runner.os }}-bun

  #     - name: üß™ Test
  #       run: bun run test 